Added files

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -21,4 +21,9 @@ jobs:
         run: make
 
       - name: App execution
-        run: ./hello
+        run: |
+            output=$(./hello)
+            if [ "${output}" != "Hello, World!" ]; then
+                echo "Error in app response"
+                exit 1
+            fi
